version: '3'

services:
  node_app_1:
    build:
      context: ./node
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      - PORT=3000
      - DB_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_HOSTS=postgres
    networks:
      - backend
      - api-ext
    ports:
      - 3000

  node_app_2:
    build:
      context: ./node
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      - PORT=3000
      - DB_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_HOSTS=postgres
    networks:
      - backend
      - api-ext
    ports:
      - 3000

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on: ["node_app_1", "node_app_2"]
    networks:
      - backend
    ports:
      - 8080:8080

  redis:
    image: redis
    networks:
      - backend
    ports:
      - 6379:6379

  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    networks:
      - backend
    ports:
      - 5432:5432
    volumes:
      - ./volumes/db:/var/lib/postgresql/data

  # nginx-api-ext-virtual:
  #   image: nginx
  #   networks:
  #     - api-ext
  #   ports:
  #     - 80:80

networks:
  backend:
    driver: bridge

  api-ext:
    external: true
